# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: NodePort
  ports:
  - port: 18081
    targetPort: 8081
  selector:
    app: python-app
